name: Build Tarnished for Android ARM64

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nsetup/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Build Engine Binary
        run: |
          NDK_BIN="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
          
          make arm64 \
            CXX="$NDK_BIN/aarch64-linux-android24-clang++ -static-libstdc++" \
            HOST_CXX="g++"

      - name: Upload Android Executable
        uses: actions/upload-artifact@v4
        with:
          name: tarnished-android-arm64
          path: tarnished
